version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: nostra_movies
      POSTGRES_PASSWORD: Nostra
      POSTGRES_DB: Nostra
    volumes:
      - "mypostgres:/var/lib/postgresql/data/" #persist data event
    ports:
      - "5432:5432"
volumes:
  mypostgres: